--- #YAML:1.0
name:                HTTP-Cookies-Omniweb
version:             1.11
abstract:            Cookie storage and management for Omniweb
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    HTTP::Cookies:                 1.25
    Text::Diff:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
