--- #YAML:1.0
name:               HTTP-Cookies-Omniweb
version:            1.12
abstract:           Cookie storage and management for Omniweb
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Cookies:  1.25
    Text::Diff:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
